<Type Name="SendAvailabilityMessagingException" FullName="Microsoft.Azure.NotificationHubs.Messaging.SendAvailabilityMessagingException">
  <TypeSignature Language="C#" Value="public class SendAvailabilityMessagingException : Microsoft.Azure.NotificationHubs.Messaging.MessagingException" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable beforefieldinit SendAvailabilityMessagingException extends Microsoft.Azure.NotificationHubs.Messaging.MessagingException" />
  <TypeSignature Language="DocId" Value="T:Microsoft.Azure.NotificationHubs.Messaging.SendAvailabilityMessagingException" />
  <TypeSignature Language="VB.NET" Value="Public Class SendAvailabilityMessagingException&#xA;Inherits MessagingException" />
  <TypeSignature Language="F#" Value="type SendAvailabilityMessagingException = class&#xA;    inherit MessagingException" />
  <AssemblyInfo>
    <AssemblyName>Microsoft.Azure.NotificationHubs</AssemblyName>
    <AssemblyVersion>2.16.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>Microsoft.Azure.NotificationHubs.Messaging.MessagingException</BaseTypeName>
  </Base>
  <Interfaces />
  <Docs>
    <summary><span data-ttu-id="b9b79-101">表しますが、メッセージングの可用性の送信中に例外が発生しました。</span><span class="sxs-lookup"><span data-stu-id="b9b79-101">Represents the exceptions occurred during the sending the availability for the messaging.</span></span></summary>
    <remarks>To be added.</remarks>
  </Docs>
  <Members>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public SendAvailabilityMessagingException (Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:Microsoft.Azure.NotificationHubs.Messaging.SendAvailabilityMessagingException.#ctor(System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (innerException As Exception)" />
      <MemberSignature Language="F#" Value="new Microsoft.Azure.NotificationHubs.Messaging.SendAvailabilityMessagingException : Exception -&gt; Microsoft.Azure.NotificationHubs.Messaging.SendAvailabilityMessagingException" Usage="new Microsoft.Azure.NotificationHubs.Messaging.SendAvailabilityMessagingException innerException" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Azure.NotificationHubs</AssemblyName>
        <AssemblyVersion>2.16.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="innerException"><span data-ttu-id="b9b79-102">例外の原因となったエラー。</span><span class="sxs-lookup"><span data-stu-id="b9b79-102">The error that caused the exception.</span></span></param>
        <summary><span data-ttu-id="b9b79-103"><see cref="T:Microsoft.Azure.NotificationHubs.Messaging.SendAvailabilityMessagingException" /> クラスの新しいインスタンスを初期化します。</span><span class="sxs-lookup"><span data-stu-id="b9b79-103">Initializes a new instance of the <see cref="T:Microsoft.Azure.NotificationHubs.Messaging.SendAvailabilityMessagingException" /> class.</span></span></summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
  </Members>
</Type>